// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TechWizards.Persistence.DataContexts;

#nullable disable

namespace TechWizards.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240914075629_Added_Assessment")]
    partial class Added_Assessment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TechWizards.Domain.Models.Entities.Assessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<byte>("Level")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Assessments");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Assessment");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TechWizards.Domain.Models.Entities.QuizAssessment", b =>
                {
                    b.HasBaseType("TechWizards.Domain.Models.Entities.Assessment");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Topics")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasDiscriminator().HasValue("QuizAssessment");
                });
#pragma warning restore 612, 618
        }
    }
}
