// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TechWizards.Persistence.DataContexts;

#nullable disable

namespace TechWizards.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240914093817_Added_Question_And_Assessment_Relation")]
    partial class Added_Question_And_Assessment_Relation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TechWizards.Domain.Models.Entities.Assessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<byte>("Level")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Assessments");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Assessment");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TechWizards.Domain.Models.Entities.QuizQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("QuizAssessmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuizAssessmentId");

                    b.ToTable("QuizQuestion");
                });

            modelBuilder.Entity("TechWizards.Domain.Models.Entities.QuizAssessment", b =>
                {
                    b.HasBaseType("TechWizards.Domain.Models.Entities.Assessment");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<List<string>>("Topics")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasDiscriminator().HasValue("QuizAssessment");
                });

            modelBuilder.Entity("TechWizards.Domain.Models.Entities.QuizQuestion", b =>
                {
                    b.HasOne("TechWizards.Domain.Models.Entities.QuizAssessment", "QuizAssessment")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("QuizAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizAssessment");
                });

            modelBuilder.Entity("TechWizards.Domain.Models.Entities.QuizAssessment", b =>
                {
                    b.Navigation("QuizQuestions");
                });
#pragma warning restore 612, 618
        }
    }
}
